// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm0P2Xjscl6BhgPCxtltDLopLZHOo9o3Y',
    appId: '1:629780857223:web:991a49a4fb36e930bc5322',
    messagingSenderId: '629780857223',
    projectId: 'beauty-bee-294ff',
    authDomain: 'beauty-bee-294ff.firebaseapp.com',
    storageBucket: 'beauty-bee-294ff.firebasestorage.app',
    measurementId: 'G-2T6G41J9R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnwzVd5pKuSvJEDqQDfilcduTA4tMnKzE',
    appId: '1:629780857223:android:7eecb1e53857d0e2bc5322',
    messagingSenderId: '629780857223',
    projectId: 'beauty-bee-294ff',
    storageBucket: 'beauty-bee-294ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJOxOZ3W2SLYMPHC6ASM8pL8pTbr6PC1Q',
    appId: '1:629780857223:ios:de80c35588852e8ebc5322',
    messagingSenderId: '629780857223',
    projectId: 'beauty-bee-294ff',
    storageBucket: 'beauty-bee-294ff.firebasestorage.app',
    iosBundleId: 'com.beautybee.app.beautybee',
  );

}